@c    
@c Copyright (C) 2006-2011 Hervé Rouault <rouault@lps.ens.fr>
@c Copyright (C) 2009-2011 Marc Santolini <santolin@lps.ens.fr>
@c 
@c This file is part of Imogene.
@c 
@c Imogene is free software: you can redistribute it and/or modify
@c it under the terms of the GNU General Public License as published by
@c the Free Software Foundation, either version 3 of the License, or
@c (at your option) any later version.
@c 
@c Imogene is distributed in the hope that it will be useful,
@c but WITHOUT ANY WARRANTY; without even the implied warranty of
@c MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
@c GNU General Public License for more details.
@c 
@c You should have received a copy of the GNU General Public License
@c along with Imogene; see the file COPYING  If not, see <http://www.gnu.org/licenses/>.

@node distinfo
@chapter Distance between PWMs

@cindex distance, PWM

@section Description of the distance

copy paste from the paper

@section Invoking the command line tool

This is the output of @code{imogene distinfo --help}:

@smallexample
@include distinfo.help
@end smallexample

You mainly need to provide two PWM files in the form of:

@smallexample
enhancer1 2L 2345  3456
enhancer2 2R 4567  5678
@end smallexample

You can find example files in the folder @file{example} of the tarball. You can then try:
@smallexample
imogene distinfo --input example/PWM1.dat example/PWM2.dat
@end smallexample

