@c    
@c Copyright (C) 2006-2011 Hervé Rouault <rouault@lps.ens.fr>
@c Copyright (C) 2009-2011 Marc Santolini <santolin@lps.ens.fr>
@c 
@c This file is part of Imogene.
@c 
@c Imogene is free software: you can redistribute it and/or modify
@c it under the terms of the GNU General Public License as published by
@c the Free Software Foundation, either version 3 of the License, or
@c (at your option) any later version.
@c 
@c Imogene is distributed in the hope that it will be useful,
@c but WITHOUT ANY WARRANTY; without even the implied warranty of
@c MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
@c GNU General Public License for more details.
@c 
@c You should have received a copy of the GNU General Public License
@c along with Imogene; see the file COPYING  If not, see <http://www.gnu.org/licenses/>.

@node Extract
@chapter Extract an alignment from a coordinate file

@cindex extract, alignment

This is the output of @code{imogene extract --help}:

@smallexample
@include extract.help
@end smallexample

You mainly need to provide a coordinate file in the BED4 format:

@smallexample
chr2L 2345  3456 enhancer1 
chr2R 4567  5678 enhancer2
@end smallexample

The coordinates should use the release 5 (or dm3) system for @emph{Drosophila Melanogaster} and the mm9 system for @emph{Mus Musculus}.
You can find example files in the folder @file{example} of the tarball. You can then try:
@smallexample
imogene extract --input example/enhancer-coords.dat
@end smallexample

