/*
  File autogenerated by gengetopt version 2.22.4
  generated with the following command:
  gengetopt --input=genmot.ggo --func-name=genmot_cmdline_parser --arg-struct-name=genmot_args_info --file-name=genmot_cmdline --unamed-opts=<motifs>

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "genmot_cmdline.h"

const char *genmot_args_info_purpose = "Genome analysis for the inference of gene cis-regulatory modules.";

const char *genmot_args_info_usage = "Usage: " GENMOT_CMDLINE_PARSER_PACKAGE " [OPTIONS]... [<motifs>]...";

const char *genmot_args_info_description = "";

const char *genmot_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "  -w, --width=int               Width of the motifs  (default=`10')",
  "  -t, --threshold=double        Threshold used for motif scanning  \n                                  (default=`9')",
  "  -x, --neighbext=int           Extent of the motif search within an alignment  \n                                  (default=`20')",
  "  -n, --nbmots=int              Number of motifs to consider at maximum  \n                                  (default=`20')",
  "  -c, --coord-file=str          File of enhancer coordinates  \n                                  (default=`coords.dat')",
  "  -a, --align-file=str          File of enhancer alignments",
  "  -e, --evolutionary-model=int  Evolutionary model used for motif generation \n                                  (1=felsen, 2=halpern)  (default=`1')",
  "  -s, --species=int             Species studied (1=droso, 2= mus)",
  "      --scanwidth=int           Width of selected enhancers  (default=`1000')",
    0
};

typedef enum {ARG_NO
  , ARG_STRING
  , ARG_INT
  , ARG_DOUBLE
} genmot_cmdline_parser_arg_type;

static
void clear_given (struct genmot_args_info *args_info);
static
void clear_args (struct genmot_args_info *args_info);

static int
genmot_cmdline_parser_internal (int argc, char **argv, struct genmot_args_info *args_info,
                        struct genmot_cmdline_parser_params *params, const char *additional_error);

static int
genmot_cmdline_parser_required2 (struct genmot_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct genmot_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->width_given = 0 ;
  args_info->threshold_given = 0 ;
  args_info->neighbext_given = 0 ;
  args_info->nbmots_given = 0 ;
  args_info->coord_file_given = 0 ;
  args_info->align_file_given = 0 ;
  args_info->evolutionary_model_given = 0 ;
  args_info->species_given = 0 ;
  args_info->scanwidth_given = 0 ;
}

static
void clear_args (struct genmot_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->width_arg = 10;
  args_info->width_orig = NULL;
  args_info->threshold_arg = 9;
  args_info->threshold_orig = NULL;
  args_info->neighbext_arg = 20;
  args_info->neighbext_orig = NULL;
  args_info->nbmots_arg = 20;
  args_info->nbmots_orig = NULL;
  args_info->coord_file_arg = gengetopt_strdup ("coords.dat");
  args_info->coord_file_orig = NULL;
  args_info->align_file_arg = NULL;
  args_info->align_file_orig = NULL;
  args_info->evolutionary_model_arg = 1;
  args_info->evolutionary_model_orig = NULL;
  args_info->species_orig = NULL;
  args_info->scanwidth_arg = 1000;
  args_info->scanwidth_orig = NULL;
  
}

static
void init_args_info(struct genmot_args_info *args_info)
{


  args_info->help_help = genmot_args_info_help[0] ;
  args_info->version_help = genmot_args_info_help[1] ;
  args_info->width_help = genmot_args_info_help[2] ;
  args_info->threshold_help = genmot_args_info_help[3] ;
  args_info->neighbext_help = genmot_args_info_help[4] ;
  args_info->nbmots_help = genmot_args_info_help[5] ;
  args_info->coord_file_help = genmot_args_info_help[6] ;
  args_info->align_file_help = genmot_args_info_help[7] ;
  args_info->evolutionary_model_help = genmot_args_info_help[8] ;
  args_info->species_help = genmot_args_info_help[9] ;
  args_info->scanwidth_help = genmot_args_info_help[10] ;
  
}

void
genmot_cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(GENMOT_CMDLINE_PARSER_PACKAGE_NAME) ? GENMOT_CMDLINE_PARSER_PACKAGE_NAME : GENMOT_CMDLINE_PARSER_PACKAGE),
     GENMOT_CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  genmot_cmdline_parser_print_version ();

  if (strlen(genmot_args_info_purpose) > 0)
    printf("\n%s\n", genmot_args_info_purpose);

  if (strlen(genmot_args_info_usage) > 0)
    printf("\n%s\n", genmot_args_info_usage);

  printf("\n");

  if (strlen(genmot_args_info_description) > 0)
    printf("%s\n\n", genmot_args_info_description);
}

void
genmot_cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (genmot_args_info_help[i])
    printf("%s\n", genmot_args_info_help[i++]);
}

void
genmot_cmdline_parser_init (struct genmot_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
genmot_cmdline_parser_params_init(struct genmot_cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct genmot_cmdline_parser_params *
genmot_cmdline_parser_params_create(void)
{
  struct genmot_cmdline_parser_params *params = 
    (struct genmot_cmdline_parser_params *)malloc(sizeof(struct genmot_cmdline_parser_params));
  genmot_cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
genmot_cmdline_parser_release (struct genmot_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->width_orig));
  free_string_field (&(args_info->threshold_orig));
  free_string_field (&(args_info->neighbext_orig));
  free_string_field (&(args_info->nbmots_orig));
  free_string_field (&(args_info->coord_file_arg));
  free_string_field (&(args_info->coord_file_orig));
  free_string_field (&(args_info->align_file_arg));
  free_string_field (&(args_info->align_file_orig));
  free_string_field (&(args_info->evolutionary_model_orig));
  free_string_field (&(args_info->species_orig));
  free_string_field (&(args_info->scanwidth_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
genmot_cmdline_parser_dump(FILE *outfile, struct genmot_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", GENMOT_CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->width_given)
    write_into_file(outfile, "width", args_info->width_orig, 0);
  if (args_info->threshold_given)
    write_into_file(outfile, "threshold", args_info->threshold_orig, 0);
  if (args_info->neighbext_given)
    write_into_file(outfile, "neighbext", args_info->neighbext_orig, 0);
  if (args_info->nbmots_given)
    write_into_file(outfile, "nbmots", args_info->nbmots_orig, 0);
  if (args_info->coord_file_given)
    write_into_file(outfile, "coord-file", args_info->coord_file_orig, 0);
  if (args_info->align_file_given)
    write_into_file(outfile, "align-file", args_info->align_file_orig, 0);
  if (args_info->evolutionary_model_given)
    write_into_file(outfile, "evolutionary-model", args_info->evolutionary_model_orig, 0);
  if (args_info->species_given)
    write_into_file(outfile, "species", args_info->species_orig, 0);
  if (args_info->scanwidth_given)
    write_into_file(outfile, "scanwidth", args_info->scanwidth_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
genmot_cmdline_parser_file_save(const char *filename, struct genmot_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", GENMOT_CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = genmot_cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
genmot_cmdline_parser_free (struct genmot_args_info *args_info)
{
  genmot_cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
genmot_cmdline_parser (int argc, char **argv, struct genmot_args_info *args_info)
{
  return genmot_cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
genmot_cmdline_parser_ext (int argc, char **argv, struct genmot_args_info *args_info,
                   struct genmot_cmdline_parser_params *params)
{
  int result;
  result = genmot_cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      genmot_cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
genmot_cmdline_parser2 (int argc, char **argv, struct genmot_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct genmot_cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = genmot_cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      genmot_cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
genmot_cmdline_parser_required (struct genmot_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (genmot_cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      genmot_cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
genmot_cmdline_parser_required2 (struct genmot_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (! args_info->species_given)
    {
      fprintf (stderr, "%s: '--species' ('-s') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  
  
  /* checks for dependences among options */

  return error;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see genmot_cmdline_parser_params.check_ambiguity
 * @param override @see genmot_cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               genmot_cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_DOUBLE:
    if (val) *((double *)field) = strtod (val, &stop_char);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_DOUBLE:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
genmot_cmdline_parser_internal (
  int argc, char **argv, struct genmot_args_info *args_info,
                        struct genmot_cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct genmot_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    genmot_cmdline_parser_init (args_info);

  genmot_cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "width",	1, NULL, 'w' },
        { "threshold",	1, NULL, 't' },
        { "neighbext",	1, NULL, 'x' },
        { "nbmots",	1, NULL, 'n' },
        { "coord-file",	1, NULL, 'c' },
        { "align-file",	1, NULL, 'a' },
        { "evolutionary-model",	1, NULL, 'e' },
        { "species",	1, NULL, 's' },
        { "scanwidth",	1, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVw:t:x:n:c:a:e:s:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          genmot_cmdline_parser_print_help ();
          genmot_cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          genmot_cmdline_parser_print_version ();
          genmot_cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'w':	/* Width of the motifs.  */
        
        
          if (update_arg( (void *)&(args_info->width_arg), 
               &(args_info->width_orig), &(args_info->width_given),
              &(local_args_info.width_given), optarg, 0, "10", ARG_INT,
              check_ambiguity, override, 0, 0,
              "width", 'w',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* Threshold used for motif scanning.  */
        
        
          if (update_arg( (void *)&(args_info->threshold_arg), 
               &(args_info->threshold_orig), &(args_info->threshold_given),
              &(local_args_info.threshold_given), optarg, 0, "9", ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "threshold", 't',
              additional_error))
            goto failure;
        
          break;
        case 'x':	/* Extent of the motif search within an alignment.  */
        
        
          if (update_arg( (void *)&(args_info->neighbext_arg), 
               &(args_info->neighbext_orig), &(args_info->neighbext_given),
              &(local_args_info.neighbext_given), optarg, 0, "20", ARG_INT,
              check_ambiguity, override, 0, 0,
              "neighbext", 'x',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* Number of motifs to consider at maximum.  */
        
        
          if (update_arg( (void *)&(args_info->nbmots_arg), 
               &(args_info->nbmots_orig), &(args_info->nbmots_given),
              &(local_args_info.nbmots_given), optarg, 0, "20", ARG_INT,
              check_ambiguity, override, 0, 0,
              "nbmots", 'n',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* File of enhancer coordinates.  */
        
        
          if (update_arg( (void *)&(args_info->coord_file_arg), 
               &(args_info->coord_file_orig), &(args_info->coord_file_given),
              &(local_args_info.coord_file_given), optarg, 0, "coords.dat", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "coord-file", 'c',
              additional_error))
            goto failure;
        
          break;
        case 'a':	/* File of enhancer alignments.  */
        
        
          if (update_arg( (void *)&(args_info->align_file_arg), 
               &(args_info->align_file_orig), &(args_info->align_file_given),
              &(local_args_info.align_file_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "align-file", 'a',
              additional_error))
            goto failure;
        
          break;
        case 'e':	/* Evolutionary model used for motif generation (1=felsen, 2=halpern).  */
        
        
          if (update_arg( (void *)&(args_info->evolutionary_model_arg), 
               &(args_info->evolutionary_model_orig), &(args_info->evolutionary_model_given),
              &(local_args_info.evolutionary_model_given), optarg, 0, "1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "evolutionary-model", 'e',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* Species studied (1=droso, 2= mus).  */
        
        
          if (update_arg( (void *)&(args_info->species_arg), 
               &(args_info->species_orig), &(args_info->species_given),
              &(local_args_info.species_given), optarg, 0, 0, ARG_INT,
              check_ambiguity, override, 0, 0,
              "species", 's',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* Width of selected enhancers.  */
          if (strcmp (long_options[option_index].name, "scanwidth") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->scanwidth_arg), 
                 &(args_info->scanwidth_orig), &(args_info->scanwidth_given),
                &(local_args_info.scanwidth_given), optarg, 0, "1000", ARG_INT,
                check_ambiguity, override, 0, 0,
                "scanwidth", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", GENMOT_CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
      error += genmot_cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  genmot_cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  
  genmot_cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
